### ISSUE TITLE
DB migration at startup fails

### ISSUE THREAD

**Issue by pavellishin** [NewPublicArtFoundation/PublicArt.io#2]
Looks like the initial DB seed data was never committed :/

```
[2015-02-03 23:46:33] pavel.lishin@plishin:~/Temp/PublicArt.io
# rake db:migrate RAILS_ENV=development
== 20141005104407 AddAddressToInstagramArt: migrating =========================
-- add_column(:instagram_arts, :address, :string)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: instagram_arts: ALTER TABLE "instagram_arts" ADD "address" varchar(255)/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:134:in `execute'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:334:in `block in execute'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:334:in `execute'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:375:in `add_column'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:457:in `add_column'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:649:in `block in method_missing'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:621:in `block in say_with_time'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:621:in `say_with_time'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:641:in `method_missing'
/Users/pavel.lishin/Temp/PublicArt.io/db/migrate/20141005104407_add_address_to_instagram_art.rb:3:in `change'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:595:in `exec_migration'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:578:in `block in migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:577:in `migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:752:in `migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/transactions.rb:208:in `transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `ddl_transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:953:in `block in migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `each'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:807:in `up'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/migration.rb:785:in `migrate'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.2/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/Users/pavel.lishin/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by pavellishin** [comment]
Oh, wait, I just needed to run `db:schema:load` first, it looks like :/

**Comment by rememberlenny** [comment]
lol :)

Leonard Bogdonoff
Lkbgift@gmail.com
Blog | Github
@rememberlenny | 949-322-8496

**Comment by pavellishin** [comment]
Huh, I guess you can comment on issues via email?

Also, everyone has your phone number now.
